---
name: homelab
services:
  # dns
  coredns:
    container_name: coredns
    image: coredns/coredns:1.12.1
    command: -conf /etc/coredns/Corefile
    networks:
      - dns_net
    ports:
      - 192.168.8.30:53:53/udp
      - 192.168.8.30:53:53/tcp
    volumes:
      - ./coredns/Corefile:/etc/coredns/Corefile:ro
    restart: unless-stopped
  # reverse proxy
  caddy:
    container_name: caddy
    image: ghcr.io/aatng-gh/homelab/caddy:2.9.1
    networks:
      - dns_net
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /data/caddy/data:/data
      - /data/caddy/config:/config
    environment:
      CF_API_TOKEN: ${CF_API_TOKEN}
    restart: unless-stopped
  # media server
  plex:
    container_name: plex
    image: plexinc/pms-docker:1.41.7.9799-5bce000f7
    networks:
      - dns_net
    ports:
      - 32400:32400/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - /data/plex/config:/config:Z
      - /data/plex/transcode:/transcode:Z
      - /data/plex/media:/data:Z
    environment:
      PLEX_UID: 0
      PLEX_GID: 0
      TZ: America/New_York
      PLEX_CLAIM: ${PLEX_CLAIM}
    restart: unless-stopped
  # vpn
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:v3.40
    networks:
      - vpn_net
    ports:
      - 8888:8888/tcp
      - 6880:6880
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
      - 3030:3030
      - 4240:4240
    volumes:
      - /data/gluetun:/gluetun
    environment:
      VPN_SERVICE_PROVIDER: surfshark
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      WIREGUARD_ADDRESSES: 10.14.0.2/16
      SERVER_COUNTRIES: United States
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  # rqbit
  rqbit:
    container_name: rqbit
    image: ikatson/rqbit:8.0
    network_mode: service:gluetun
    volumes:
      - /data/rqbit/db:/home/rqbit/db:Z
      - /data/rqbit/cache:/home/rqbit/cache:Z
      - /data/plex/media:/home/rqbit/downloads:Z
    environment:
      HOME: /home/rqbit
    restart: unless-stopped
networks:
  dns_net:
    driver: bridge
  vpn_net:
    driver: bridge
